'use strict';

blocktoolApp.factory('VendorDevice', function() {

  var data = {
  "data":
  [
    {
      "id": 1,
      "vid": 0,
      "did": 1,
      "device_type": "temperature",
      "default_name": "Block Temperature",
      "tags": "sensor cape temp celsius",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 2,
      "vid": 0,
      "did": 2,
      "device_type": "orientation",
      "default_name": "Block Accelerometer",
      "tags": "sensor cape accelerometer orientation",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 3,
      "vid": 0,
      "did": 3,
      "device_type": "jiggle",
      "default_name": "Block Jiggle",
      "tags": "sensor cape accelerometer acceleration",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 4,
      "vid": 0,
      "did": 5,
      "device_type": "button",
      "default_name": "Push Button",
      "tags": "sensor serial pushbutton",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 5,
      "vid": 0,
      "did": 6,
      "device_type": "light_level",
      "default_name": "Light Sensor",
      "tags": "sensor serial analog light",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 6,
      "vid": 0,
      "did": 7,
      "device_type": "pir",
      "default_name": "PIR Motion Sensor",
      "tags": "sensor serial analog pir",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 7,
      "vid": 0,
      "did": 8,
      "device_type": "humidity",
      "default_name": "Humidity",
      "tags": "sensor serial dht22 digital humidity",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 8,
      "vid": 0,
      "did": 9,
      "device_type": "temperature",
      "default_name": "Temperature",
      "tags": "sensor serial dht22 digital temp celsius",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 9,
      "vid": 0,
      "did": 10,
      "device_type": "distance",
      "default_name": "Distance Sensor",
      "tags": "sensor serial analog distance",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": "{\"dataTransform\":\"syncSamsungDistance\"}"
    },
    {
      "id": 10,
      "vid": 0,
      "did": 11,
      "device_type": "rf433",
      "default_name": "RF 433Mhz",
      "tags": "sensor serial rf rf433 receiver transmitter",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 1,
      "system": null
    },
    {
      "id": 11,
      "vid": 0,
      "did": 12,
      "device_type": "sound",
      "default_name": "Sound Sensor",
      "tags": "sensor serial sound",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 31,
      "vid": 0,
      "did": 13,
      "device_type": "temperature",
      "default_name": "La Crosse Temp TX3/6",
      "tags": "sensor rf digital temp celsius",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 30,
      "vid": 0,
      "did": 14,
      "device_type": "hid",
      "default_name": "Unknown HID Device",
      "tags": "sensor hid",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 32,
      "vid": 0,
      "did": 20,
      "device_type": "temperature",
      "default_name": "La Crosse Temp WS2355",
      "tags": "sensor rf digital temp celsius",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 33,
      "vid": 0,
      "did": 21,
      "device_type": "humidity",
      "default_name": "La Crosse Humidity WS2355",
      "tags": "sensor rf digital humidity",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 34,
      "vid": 0,
      "did": 22,
      "device_type": "rainfall",
      "default_name": "La Crosse Rainfall WS2355",
      "tags": "sensor rf rainfall",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 35,
      "vid": 0,
      "did": 23,
      "device_type": "direction",
      "default_name": "La Crosse Wind Direction",
      "tags": "sensor rf wind direction",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 36,
      "vid": 0,
      "did": 24,
      "device_type": "speed",
      "default_name": "La Crosse Wind Speed",
      "tags": "sensor rf wind speed",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 37,
      "vid": 0,
      "did": 30,
      "device_type": "humidity",
      "default_name": "Humidity",
      "tags": "sensor rf digital humidity",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 38,
      "vid": 0,
      "did": 31,
      "device_type": "temperature",
      "default_name": "Temperature",
      "tags": "sensor rf digital temperature celsius",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 21,
      "vid": 0,
      "did": 101,
      "device_type": "twitter",
      "default_name": "Twitter",
      "tags": "sensor actuator webservice virtual twitter",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 1,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 22,
      "vid": 0,
      "did": 102,
      "device_type": "facebook",
      "default_name": "Facebook",
      "tags": "sensor actuator webservice virtual facebook",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 1,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 23,
      "vid": 0,
      "did": 103,
      "device_type": "sms",
      "default_name": "SMS",
      "tags": "sensor actuator webservice virtual twilio",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 1,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 24,
      "vid": 0,
      "did": 104,
      "device_type": "dropbox",
      "default_name": "Dropbox",
      "tags": "sensor actuator webservice virtual dropbox",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 1,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 25,
      "vid": 0,
      "did": 105,
      "device_type": "googledrive",
      "default_name": "Google Drive",
      "tags": "sensor actuator webservice virtual google",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 1,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 26,
      "vid": 0,
      "did": 106,
      "device_type": "email",
      "default_name": "Email",
      "tags": "sensor actuator webservice virtual email",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 1,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 27,
      "vid": 0,
      "did": 107,
      "device_type": "salesforce",
      "default_name": "Salesforce",
      "tags": "sensor actuator webservice virtual salesforce",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 1,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 28,
      "vid": 0,
      "did": 108,
      "device_type": "webhook",
      "default_name": "Webhook",
      "tags": "sensor actuator webservice virtual webhook",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 1,
      "has_time_series": 0,
      "has_subdevice_count": 1,
      "system": null
    },
    {
      "id": 57,
      "vid": 0,
      "did": 200,
      "device_type": "button",
      "default_name": "Push Button",
      "tags": "generic sensor button",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 58,
      "vid": 0,
      "did": 201,
      "device_type": "momentary_switch",
      "default_name": "Reed Switch",
      "tags": "generic sesnor switch magnetic_switch reed_switch",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 59,
      "vid": 0,
      "did": 202,
      "device_type": "temperature",
      "default_name": "Temperature",
      "tags": "generic sensor temperature celsius",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 60,
      "vid": 0,
      "did": 203,
      "device_type": "humidity",
      "default_name": "Humidity",
      "tags": "generic sensor humidity",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 61,
      "vid": 0,
      "did": 204,
      "device_type": "pir",
      "default_name": "PIR Motion Sensor",
      "tags": "generic sensor PIR motion movement",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 62,
      "vid": 0,
      "did": 205,
      "device_type": "switch_sensor",
      "default_name": "Switch Sensor",
      "tags": "generic sensor switch",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 63,
      "vid": 0,
      "did": 206,
      "device_type": "switch_actuator",
      "default_name": "Switch Actuator",
      "tags": "generic actuator switch",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 64,
      "vid": 0,
      "did": 207,
      "device_type": "switch",
      "default_name": "Switch",
      "tags": "generic actuator sensor switch",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 65,
      "vid": 0,
      "did": 208,
      "device_type": "orientation",
      "default_name": "Orientation",
      "tags": "generic sensor orientation",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 66,
      "vid": 0,
      "did": 209,
      "device_type": "jiggle",
      "default_name": "Jiggle",
      "tags": "generic sensor jiggle",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 67,
      "vid": 0,
      "did": 210,
      "device_type": "gesture",
      "default_name": "Gesture",
      "tags": "generic sensor gesture",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 68,
      "vid": 0,
      "did": 211,
      "device_type": "keyboard",
      "default_name": "Keyboard",
      "tags": "generic sensor keyboard character",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 69,
      "vid": 0,
      "did": 212,
      "device_type": "code_reader",
      "default_name": "Barcode Scanner",
      "tags": "generic sensor barcode scanner reader",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 70,
      "vid": 0,
      "did": 213,
      "device_type": "code_reader",
      "default_name": "QR code Scanner",
      "tags": "generic sensor qrcode scanner reader",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 71,
      "vid": 0,
      "did": 214,
      "device_type": "distance",
      "default_name": "Distance",
      "tags": "generic sensor distance",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 72,
      "vid": 0,
      "did": 215,
      "device_type": "sound",
      "default_name": "Sound ",
      "tags": "generic sensor sound volume",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 73,
      "vid": 0,
      "did": 216,
      "device_type": "microphone",
      "default_name": "Microphone",
      "tags": "generic sensor microphone audio",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 74,
      "vid": 0,
      "did": 217,
      "device_type": "hid",
      "default_name": "HID Device",
      "tags": "generic sensor character hid reader",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 1,
      "system": null
    },
    {
      "id": 75,
      "vid": 0,
      "did": 218,
      "device_type": "rfid",
      "default_name": "RFID Reader",
      "tags": "generic sensor rfid reader",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 1,
      "system": null
    },
    {
      "id": 76,
      "vid": 0,
      "did": 219,
      "device_type": "proximity",
      "default_name": "Proximity Sensor",
      "tags": "generic sensor proximity",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 77,
      "vid": 0,
      "did": 220,
      "device_type": "camera_still",
      "default_name": "Camera",
      "tags": "generic sensor camera still snapshot",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 78,
      "vid": 0,
      "did": 221,
      "device_type": "camera_video",
      "default_name": "Video Camera",
      "tags": "generic sensor camera video",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 79,
      "vid": 0,
      "did": 222,
      "device_type": "compass",
      "default_name": "Compass",
      "tags": "generic sensor compass direction",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 80,
      "vid": 0,
      "did": 223,
      "device_type": "location",
      "default_name": "Location",
      "tags": "generic sensor location latlong",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 81,
      "vid": 0,
      "did": 224,
      "device_type": "light",
      "default_name": "Light",
      "tags": "generic sensor light percentage",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 82,
      "vid": 0,
      "did": 225,
      "device_type": "moisture",
      "default_name": "Moisture",
      "tags": "generic sensor moisture",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 83,
      "vid": 0,
      "did": 226,
      "device_type": "ph",
      "default_name": "pH Sensor",
      "tags": "generic sensor ph",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 84,
      "vid": 0,
      "did": 227,
      "device_type": "geiger",
      "default_name": "Geiger Counter",
      "tags": "generic sensor geiger radiation",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 85,
      "vid": 0,
      "did": 228,
      "device_type": "rf",
      "default_name": "RF Transceiver",
      "tags": "generic sensor actuator rf",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 1,
      "system": null
    },
    {
      "id": 86,
      "vid": 0,
      "did": 229,
      "device_type": "zigbee",
      "default_name": "Zigbee Transceiver",
      "tags": "generic sensor actuator zigbee",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 1,
      "system": null
    },
    {
      "id": 87,
      "vid": 0,
      "did": 230,
      "device_type": "zwave",
      "default_name": "Z-wave Transceiver",
      "tags": "generic sensor actuator zwave",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 1,
      "system": null
    },
    {
      "id": 88,
      "vid": 0,
      "did": 231,
      "device_type": "alarm",
      "default_name": "Alarm",
      "tags": "generic actuator alarm siren",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 89,
      "vid": 0,
      "did": 232,
      "device_type": "speaker",
      "default_name": "Speaker",
      "tags": "generic actuator speaker audio",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 90,
      "vid": 0,
      "did": 233,
      "device_type": "light_onoff",
      "default_name": "Light",
      "tags": "generic actuator light switch",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 136,
      "vid": 0,
      "did": 233,
      "device_type": "light_switch",
      "default_name": "Light",
      "tags": "generic actuator light switch",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 91,
      "vid": 0,
      "did": 234,
      "device_type": "light_dim",
      "default_name": "Light (Dimmable)",
      "tags": "generic actuator light dimmable dimmer",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 92,
      "vid": 0,
      "did": 235,
      "device_type": "rgbled8",
      "default_name": "RGB Light (Basic)",
      "tags": "generic actuator rgbled rgbled8 8colour",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 93,
      "vid": 0,
      "did": 236,
      "device_type": "rgbled",
      "default_name": "RGB Light",
      "tags": "generic actuator rgbled ",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 94,
      "vid": 0,
      "did": 237,
      "device_type": "servo",
      "default_name": "Servo",
      "tags": "generic actuator servo motor",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 95,
      "vid": 0,
      "did": 238,
      "device_type": "relay",
      "default_name": "Relay",
      "tags": "generic actuator relay",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 96,
      "vid": 0,
      "did": 239,
      "device_type": "stepper",
      "default_name": "Stepper",
      "tags": "generic actuator stepper motor",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 97,
      "vid": 0,
      "did": 240,
      "device_type": "display_text",
      "default_name": "Text Display",
      "tags": "generic actuator text display",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 98,
      "vid": 0,
      "did": 241,
      "device_type": "display_image",
      "default_name": "Display",
      "tags": "generic actuator bitmap display",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 148,
      "vid": 0,
      "did": 242,
      "device_type": "light",
      "default_name": "Light",
      "tags": "generic light on bri hue sat xy ct alert transitionTime",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 40,
      "vid": 0,
      "did": 500,
      "device_type": "location",
      "default_name": "Browser GPS",
      "tags": "sensor location gps",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 42,
      "vid": 0,
      "did": 999,
      "device_type": "rgbled",
      "default_name": "On Board RGB LED v2",
      "tags": "actuator cape led rgbled spectrum",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 53,
      "vid": 0,
      "did": 999,
      "device_type": "rgbled8",
      "default_name": "Status Light",
      "tags": "actuator cape rgbled8 rgbled led",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 12,
      "vid": 0,
      "did": 1000,
      "device_type": "rgbled8",
      "default_name": "On Board RGB LED",
      "tags": "actuator cape led rgbled",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 29,
      "vid": 0,
      "did": 1002,
      "device_type": "relay",
      "default_name": "Relay Board",
      "tags": "actuator breakout relay",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 55,
      "vid": 0,
      "did": 1003,
      "device_type": "system",
      "default_name": "Arduino Version",
      "tags": "system cape",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 13,
      "vid": 0,
      "did": 1004,
      "device_type": "webcam",
      "default_name": "Web Cam",
      "tags": "sensor actuator usb camera webcam",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 41,
      "vid": 0,
      "did": 1005,
      "device_type": "network",
      "default_name": "Network",
      "tags": "sensor actuator network system",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 1,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 56,
      "vid": 0,
      "did": 1006,
      "device_type": "speech",
      "default_name": "USB Text to Speech",
      "tags": "actuator speech speaker",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 54,
      "vid": 0,
      "did": 1007,
      "device_type": "rgbled",
      "default_name": "Nina's Eyes",
      "tags": "actuator cape rgbled led",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 145,
      "vid": 0,
      "did": 1008,
      "device_type": "light",
      "default_name": "Philips Hue",
      "tags": "light on bri hue sat xy ct alert transitionTime",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 146,
      "vid": 0,
      "did": 2000,
      "device_type": "sandbox",
      "default_name": "Sandbox",
      "tags": "sandbox",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 1,
      "system": null
    },
    {
      "id": 44,
      "vid": 0,
      "did": 7000,
      "device_type": "matrix_display",
      "default_name": "LED Board",
      "tags": "actuator",
      "is_sensor": 0,
      "is_actuator": 1,
      "is_silent": 1,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 47,
      "vid": 0,
      "did": 9001,
      "device_type": "metric",
      "default_name": "Connected Blocks",
      "tags": "sensor",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 51,
      "vid": 0,
      "did": 9002,
      "device_type": "metric",
      "default_name": "Redis Response Time",
      "tags": "sensor",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 52,
      "vid": 0,
      "did": 9003,
      "device_type": "metric",
      "default_name": "MySQL Response Time",
      "tags": "sensor",
      "is_sensor": 1,
      "is_actuator": 0,
      "is_silent": 0,
      "has_time_series": 1,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 147,
      "vid": 3012,
      "did": 9714,
      "device_type": "airconditioner",
      "default_name": "Air Conditioner",
      "tags": "aircon",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    },
    {
      "id": 39,
      "vid": 0,
      "did": 10000,
      "device_type": "led",
      "default_name": "Browser LED",
      "tags": "actuator led",
      "is_sensor": 1,
      "is_actuator": 1,
      "is_silent": 0,
      "has_time_series": 0,
      "has_subdevice_count": 0,
      "system": null
    }
  ]
};

  return data;

});
